### ISSUE TITLE
在mumu模拟器上使用发生错误

### ISSUE THREAD

**Issue by sbbbsbbb** [tomxin7/DouYinFaceTech#1]
Traceback (most recent call last):
  File "FaceMain.py", line 9, in <module>
    token = get_token(host)
  File "C:\Users\kristina\DouYinFaceTech\GetFaceInfo.py", line 15, in get_token
    res = request.urlopen(req)
  File "C:\Users\kristina\Miniconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\kristina\Miniconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\kristina\Miniconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\kristina\Miniconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\kristina\Miniconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\kristina\Miniconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by tomxin7** [comment]
百度API的参数是不是都替换了

**Comment by sbbbsbbb** [comment]
Traceback (most recent call last):
  File "FaceMain.py", line 16, in <module>
    face_dict = getBaiDuFaceTech("face.jpg",token )
  File "C:\Users\kristina\Downloads\Compressed\DouYinFaceTech-master\DouYinFaceTech-master\GetFaceInfo.py", line 53, in getBaiDuFaceTech
    if face_json["result_num"]==0:
KeyError: 'result_num'

**Comment by sbbbsbbb** [comment]
百度API的参数都替换了

**Comment by eric1932** [comment]
> Traceback (most recent call last):
> File "FaceMain.py", line 16, in 
> face_dict = getBaiDuFaceTech("face.jpg",token )
> File "C:\Users\kristina\Downloads\Compressed\DouYinFaceTech-master\DouYinFaceTech-master\GetFaceInfo.py", line 53, in getBaiDuFaceTech
> if face_json["result_num"]==0:
> KeyError: 'result_num'

遇到了同样的错误，请问是否有现成的解决办法

**Comment by eric1932** [comment]
![image](https://user-images.githubusercontent.com/10938293/52762602-ea7f4d00-2fdd-11e9-9927-4a48e49ce33b.png)

提示没有权限
